apiVersion: v1
kind: Service
metadata:
  name: jitsi-meet
  namespace: jitsi
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  - port: 443
    targetPort: 443
  selector:
    app: jitsi-meet
